apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}
  name: {{ include "netmaker.fullname" . }}
spec:
    replicas: {{ .Values.server.replicas }}
    selector:
     matchLabels:
        app: {{ include "netmaker.fullname" . }}
    serviceName: {{ include "netmaker.fullname" . }}-rest
    template:
        metadata:
            labels:
                app: {{ include "netmaker.fullname" . }}
        spec:
            containers:
            - name: {{ include "netmaker.fullname" . }}
              envFrom:
                - configMapRef:
                    name: {{ include "netmaker.fullname" . }}-env
              {{- if .Values.db.existingSecret.enabled }}
              env:
                - name: SQL_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.db.existingSecret.name }}
                      key: {{ .Values.db.existingSecret.keys.host }}
                - name: SQL_PORT
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.db.existingSecret.name }}
                      key: {{ .Values.db.existingSecret.keys.port }}
                - name: SQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.db.existingSecret.name }}
                      key: {{ .Values.db.existingSecret.keys.username }}
                - name: SQL_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.db.existingSecret.name }}
                      key: {{ .Values.db.existingSecret.keys.password }}
                - name: SQL_DB
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.db.existingSecret.name }}
                      key: {{ .Values.db.existingSecret.keys.database }}
              {{- end }}
              image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
              imagePullPolicy: {{ .Values.server.image.pullPolicy }}
              ports:
              - containerPort: {{ .Values.service.restPort }}
                protocol: TCP
            {{- if .Values.dns.enabled }}
              volumeMounts:
              - mountPath: /etc/netmaker/
                name: shared-data
              - mountPath: /root/config/dnsconfig
                name: {{ include "netmaker.fullname" . }}-dns-pvc
            volumes:
            - name: shared-data
              persistentVolumeClaim:
                claimName: {{ include "netmaker.fullname" . }}-shared-data-pvc
            - name: {{ include "netmaker.fullname" . }}-dns-pvc
              persistentVolumeClaim:
                claimName: {{ include "netmaker.fullname" . }}-dns-pvc
            {{- end }}
---
 {{- if .Values.dns.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netmaker.fullname" . }}-shared-data-pvc
spec:
  storageClassName: {{ .Values.server.RWX.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.server.storageSize }}
{{- end }}